server:
  port: 8095

spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:postgresql://localhost:5433/pedidodb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
      database:
        platform: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      clientesCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      productosCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      clientesCB:
        maxAttempts: 3
        waitDuration: 500ms
      productosCB:
        maxAttempts: 3
        waitDuration: 500ms

cliente-service:
  url: http://localhost:8090
producto-service:
  url: http://localhost:8090

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG

