server:
  port: 8092

spring:
  application:
    name: PRODUCTOSERVICIO
  datasource:
    url: jdbc:postgresql://localhost:5433/productosdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver


