server:
  port: 8092

spring:
  application:
    name: producto-service
  datasource:
    url: jdbc:postgresql://localhost:5433/productosdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
      database:
        platform: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

  # Opcional: configuración de zona horaria
  jackson:
    time-zone: Europe/Madrid


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}


